### ISSUE TITLE
error TypeError: __new__() got an unexpected keyword argument 'deny_new'

### ISSUE THREAD

**Issue by tarneaux** [adriansteffan/DiscordJockey#6]
`bash Startup.sh`
Traceback (most recent call last):
  File "run.py", line 47, in <module>
    bot.run(token, bot=True, reconnect=True)
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/client.py", line 598, in run
    return future.result()
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/client.py", line 457, in connect
    await self._connect()
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/client.py", line 421, in _connect
    await self.ws.poll_event()
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/gateway.py", line 423, in received_message
    func(data)
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/state.py", line 663, in parse_guild_create
    guild = self._get_create_guild(data)
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/state.py", line 638, in _get_create_guild
    guild._from_data(data)
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/guild.py", line 391, in _from_data
    self._sync(guild)
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/guild.py", line 418, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/channel.py", line 107, in __init__
    self._update(guild, data)
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "/home/max/.anaconda3/lib/python3.8/site-packages/discord/abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new
help?

**Comment by wasi-master** [comment]
This got fixed in an update, to update:

```bash
python3 -m pip install -U discord.py```

That's it
